name: HASPlugin
version: 2.4.4
# '${project.version}'
main: de.vmoon.hasplugin.HASPlugin
api-version: '1.20'
authors: [VoidableMoon]
description: A Hide and Seek Plugin by VoidableMoon884
website: https://vmoon.de/
commands:
  has:
    description: The main Hide-and-Seek Command
    usage: /has [stop|cancel|select|teleportall]
    permission: has.run
    children:
      has.cancel:
        description: Bricht ein laufendes Spiel ab.
        permission: has.cancel
      has.stop:
        description: Bricht den laufenden Timer ab.
        permission: has.stop
      has.select:
        description: Wählt einen Spieler als Sucher aus.
        permission: has.select
        children:
          has.select.random:
            description: Wählt einen zufälligen Spieler aus.
            permission: has.select.random
      has.teleportall:
        description: Teleportiert alle Spieler zu den Koordinaten in der Config.
        permission: has.teleportall
      has.reload:
        description: Lädt die Config Datei neu.
        permission: has.reload
      has.help:
        description: Hilfe für den Befehl
        permission: has.help
  pvp:
    description: Aktiviert oder deaktiviert PVP.
    usage: /pvp [on|off]
    permission: pvp.use
    children:
      pvp.on:
        description: Aktiviert PVP.
        permission: pvp.on
      pvp.off:
        description: Deaktiviert PVP.
        permission: pvp.off
  hashelp:
    description: Hilfe für die befehle
    usage: /hashelp {befehl}
    permission: hashelp.use
    children:
      hashelp.cancel:
        description: Hilfe für /has cancel
        permission: hashelp.cancel
      hashelp.reload:
        description: Hilfe für /has reload
        permission: hashelp.reload
      hashelp.select:
        description: Hilfe für /has select
        permission: hashelp.select
      hashelp.stop:
        description: Hilfe für /has stop
        permission: hashelp.stop
      hashelp.teleportall:
        description: Hilfe für /has teleportall
        permission: hashelp.teleportall
      hashelp.help:
        description: Zeigt diese Hilfe.
        permission: hashelp.help
permissions:
  has.run:
    description: The main Hide-and-Seek Command
    default: true
  has.cancel:
    description: Bricht ein laufendes Spiel ab.
    default: op
  has.stop:
    description: Bricht den laufenden Timer ab.
    default: op
  has.select:
    description: Wählt einen Spieler als Sucher aus.
    default: op
  has.select.random:
    description: Wählt einen zufälligen Spieler aus.
    default: op
  has.teleportall:
    description: Teleportiert alle Spieler zu den Koordinaten in der Config.
    default: op
  has.reload:
    description: Lädt die Config Datei neu.
    default: op
  has.help:
    description: Befehl für Hilfe
    default: op
  pvp.use:
    description: Aktiviert oder Deaktiviert PVP.
    default: op
  pvp.on:
    description: Aktiviert PVP.
    default: op
  pvp.off:
    description: Deaktiviert PVP.
    default: op
  hashelp.use:
    description: Hilfe für /has
    default: op
  hashelp.cancel:
    description: Hilfe für /has cancel
    default: op
  hashelp.reload:
    description: Hilfe für /has reload
    default: op
  hashelp.select:
    description: Hilfe für /has select
    default: op
  hashelp.stop:
    description: Hilfe für /has stop
    default: op
  hashelp.teleportall:
    description: Hilfe für /has teleportall
    default: op
  hashelp.help:
    description: Zeigt dieses Hilfe.
    default: op