name: HASPlugin
version: 2.4.1
# '${project.version}'
main: de.vmoon.hasplugin.HASPlugin
api-version: '1.20'
authors: [VoidableMoon]
description: A Hide and Seek Plugin by VoidableMoon884
website: https://vmoon.de/
commands:
  has:
    description: The main Hide-and-Seek Command
    usage: /has [stop|cancel|select|teleportall]
    permission: has.run
    children:
      has.cancel:
        description: Bricht ein laufendes Spiel ab.
        permission: has.cancel
      has.stop:
        description: Bricht den laufenden Timer ab.
        permission: has.stop
      has.select:
        description: Wählt einen Spieler als Sucher aus.
        permission: has.select
        children:
          has.select.random:
            description: Wählt einen zufälligen Spieler aus.
            permission: has.select.random
      has.teleportall:
        description: Teleportiert alle Spieler zu den Koordinaten in der Config.
        permission: has.teleportall
      has.reload:
        description: Lädt die Config Datei neu.
        permission: has.reload
  pvp:
    description: Aktiviert oder deaktiviert PVP.
    usage: /pvp [on|off]
    permission: pvp.use
    children:
      pvp.on:
        description: Aktiviert PVP.
        permission: pvp.on
      pvp.off:
        description: Deaktiviert PVP.
        permission: pvp.off
  hashelp:
    description: Hilfe für die befehle
    usage: /hashelp {befehl}
    permission: has.help
    children:
      has.help.cancel:
        description: Hilfe für /has cancel
        permission: has.help.cancel
      has.help.reload:
        description: Hilfe für /has reload
        permission: has.help.reload
      has.help.select:
        description: Hilfe für /has select
        permission: has.help.select
      has.help.stop:
        description: Hilfe für /has stop
        permission: has.help.stop
      has.help.teleportall:
        description: Hilfe für /has teleportall
        permission: has.help.teleportall
permissions:
  has.run:
    description: The main Hide-and-Seek Command
    default: true
  has.cancel:
    description: Bricht ein laufendes Spiel ab.
    default: op
  has.stop:
    description: Bricht den laufenden Timer ab.
    default: op
  has.select:
    description: Wählt einen Spieler als Sucher aus.
    default: op
  has.select.random:
    description: Wählt einen zufälligen Spieler aus.
    default: op
  has.teleportall:
    description: Teleportiert alle Spieler zu den Koordinaten in der Config.
    default: op
  has.reload:
    description: Lädt die Config Datei neu.
    default: op
  pvp.use:
    description: Aktiviert oder Deaktiviert PVP.
    default: op
  pvp.on:
    description: Aktiviert PVP.
    default: op
  pvp.off:
    description: Deaktiviert PVP.
    default: op